# 포트 설정
server:
  port: 9000

# 스프링 설정
spring:
  # JSP 설정
  # 포워드를 JSP에서 Tiles로 변경했으므로 주석 처리함
  # mvc:
  #   view:
  #     prefix: /WEB-INF/
  #     suffix: .jsp

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

  # gangsa MySQL 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-pf2ak-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: study1234!

# MyBatis 설정
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
    - /mapper/**/*.xml

ncp:
  storage:
    region: kr-standard
    endpoint: https://kr.object.ncloudstorage.com
    accessKey: A252DF814BA7C672CD48
    secretKey: 46D6404D168813DE822E4CC13C55346DFB47D3E1
    bucket-name: allio
