# 포트 설정
server:
  port: 9000

# 스프링 설정
spring:
  # JSP 설정
  # 포워드를 JSP에서 Tiles로 변경했으므로 주석 처리함
  # mvc:
  #   view:
  #     prefix: /WEB-INF/
  #     suffix: .jsp

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

  messages:
    basename: messages/messages
    encoding: UTF-8
    use-code-as-default-message: false
    fallback-to-system-locale: false
    cache-duration: 3600
    always-use-message-format: true

  # gangsa MySQL 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-pf2ak-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: study1234!

  # 이메일 설정
  mail:
    host: smtp.naver.com
    username: wjstnals5@naver.com
    password: Aa2330680
    port: 465
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.naver.com
            enable: true
          debug: true

# MyBatis 설정
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
    - /mapper/**/*.xml


ncp:
  storage:
    region: kr-standard
    endpoint: https://kr.object.ncloudstorage.com
    accessKey: A252DF814BA7C672CD48
    secretKey: 46D6404D168813DE822E4CC13C55346DFB47D3E1
    bucket-name: allio

cos:
  key: cos1234

